//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WindowsFormsApp5
{
    using System;
    using System.Collections.Generic;
    
    public partial class Sach
    {
        public string MaSach { get; set; }
        public string Ten_sach { get; set; }
        public string MaTG { get; set; }
        public string Linh_vuc { get; set; }
        public Nullable<decimal> Gia_mua { get; set; }
        public Nullable<decimal> Gia_bia { get; set; }
        public Nullable<int> Lan_tai_ban { get; set; }
        public string Ten_nha_xuat_ban { get; set; }
        public Nullable<System.DateTime> Nam_xuat_ban { get; set; }
    
        public virtual Tac_gia Tac_gia { get; set; }
    }
}
