//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WindowsFormsApp5
{
    using System;
    using System.Collections.Generic;
    
    public partial class Tac_gia
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Tac_gia()
        {
            this.Saches = new HashSet<Sach>();
        }
    
        public string MaTG { get; set; }
        public string Ten_tac_gia { get; set; }
        public string Que_quan { get; set; }
        public Nullable<System.DateTime> Nam_sinh { get; set; }
        public Nullable<System.DateTime> Nam_mat { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Sach> Saches { get; set; }
    }
}
